<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="IN15I51216GR512" failures="4" tests="7" name="Demo Blaze Functional Tests" time="91.288" errors="0" timestamp="2025-02-17T02:41:04 IST">
  <testcase classname="nnd.TestCases.DB_RegisterTest" name="validUserSignUp" time="10.429">
    <failure type="java.lang.AssertionError" message="Signup failed expected [Sign up successful.] but found [This user already exist.]">
      <![CDATA[java.lang.AssertionError: Signup failed expected [Sign up successful.] but found [This user already exist.]
at nnd.Pages.DB_RegisterPage.clickSignUp(DB_RegisterPage.java:67)
at nnd.TestCases.DB_RegisterTest.validUserSignUp(DB_RegisterTest.java:61)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- validUserSignUp -->
  <testcase classname="nnd.TestCases.DB_RegisterTest" name="validUserSignUp" time="10.396">
    <failure type="java.lang.AssertionError" message="Signup failed expected [Sign up successful.] but found [This user already exist.]">
      <![CDATA[java.lang.AssertionError: Signup failed expected [Sign up successful.] but found [This user already exist.]
at nnd.Pages.DB_RegisterPage.clickSignUp(DB_RegisterPage.java:67)
at nnd.TestCases.DB_RegisterTest.validUserSignUp(DB_RegisterTest.java:61)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- validUserSignUp -->
  <testcase classname="nnd.TestCases.DB_LoginTest" name="validUserLogin" time="5.45"/>
  <testcase classname="nnd.TestCases.DB_LoginTest" name="validUserLogin" time="5.443"/>
  <testcase classname="nnd.TestCases.DB_LoginTest" name="inValidUserLogin" time="8.415">
    <failure type="java.lang.AssertionError" message="Log in failed expected [Log in successful.] but found [User does not exist.]">
      <![CDATA[java.lang.AssertionError: Log in failed expected [Log in successful.] but found [User does not exist.]
at nnd.Pages.DB_LoginPage.loginAlertHandle(DB_LoginPage.java:126)
at nnd.TestCases.DB_LoginTest.inValidUserLogin(DB_LoginTest.java:87)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- inValidUserLogin -->
  <testcase classname="nnd.TestCases.DB_LoginTest" name="inValidUserLogin" time="8.4">
    <failure type="java.lang.AssertionError" message="Log in failed expected [Log in successful.] but found [User does not exist.]">
      <![CDATA[java.lang.AssertionError: Log in failed expected [Log in successful.] but found [User does not exist.]
at nnd.Pages.DB_LoginPage.loginAlertHandle(DB_LoginPage.java:126)
at nnd.TestCases.DB_LoginTest.inValidUserLogin(DB_LoginTest.java:87)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- inValidUserLogin -->
  <testcase classname="nnd.TestCases.DB_HomeTest" name="verifyPurchaseItem" time="6.702"/>
</testsuite> <!-- Demo Blaze Functional Tests -->
